const ProjectsData = [
  {
    title: 'TypeForce',
    role: 'Creator',
    url: 'https://www.typeforce.app',
    img: 'typeforce.png',
    info: 'A service that helps type foundries protect and secure their font files, while still allowing customers the ability to try before they buy.',
  },
  {
    title: 'Acrobatiq',
    role: 'Product Lead',
    url: 'https://acrobatiq.us',
    img: 'acro.jpg',
    info: 'Acrobatiq is a learning-science based, course creation and delivery platform that optimizes teaching, learning, and the course creation process.',
  },
  {
    title: 'Automated Insights',
    role: 'Head of Product',
    url: 'https://automatedinsights.com',
    img: 'ai.jpg',
    info: 'Applying natural language generation (NLG) technology to enterprise big data. We bring augmented analytics, powered by NLG, to business intelligence for the world\'s biggest brands.',
  },
  {
    title: 'Bookshelf',
    role: 'Sr. Product Manager',
    url: 'https://get.vitalsource.com',
    img: 'bookshelf2.jpg',
    info: 'The most used textbook reader in higher education with apps on iOS, Android, Mac, Windows, Chromebook and Kindle.',
  },
  {
    title: 'RatingFive (Sold)',
    role: 'Founder',
    url: 'https://ratingfive.com',
    img: 'ratingfive.png',
    info: 'Software that delivers a continous flow of five star reviews from real customers on sites like Google, Yelp, Facebook, and Healthgrades.',
  },
  {
    title: 'First.io',
    role: 'Advisor',
    url: 'https://first.io',
    img: 'first.png',
    info: 'Predictive analytics and machine learning to help real estate agents discover who in their network will soon buy or sell.',
  },
  {
    title: 'SnapSuggest (Sold)',
    role: 'Creator',
    url: 'https://snapsuggest.com',
    img: 'snapsuggest.jpg',
    info: 'A simple, easy-to-use suggestion box app on iPhone, Android and the web. Improve employee engagement and gather actionable feedback from your team.',
  },
  {
    title: 'LoyaltyGrades (Acquired)',
    role: 'Co-founder',
    url: 'https://loyaltygrades.com',
    img: 'lg.jpg',
    info: 'A new approach to healthcare surveys. Measure physician and practice performance using point-of-care surveys on iPads.',
  },
  {
    title: 'Hello (Acquired by Uber)',
    role: 'Product / Growth',
    url: 'https://web.archive.org/web/20150906003830/https://play.google.com/store/apps/details?id=com.hellotext.hello',
    img: 'hellosms.jpg',
    info: 'The first messaging app with tabs. A streamlined way to text: no inbox, no clutter, no ads. Just you and your conversations. It\'s the fastest way to chat.',
  },
  {
    title: 'Tred',
    role: 'Product Designer',
    url: 'https://tred.com',
    img: 'tred3.jpg',
    info: 'Online marketplace to buy and sell used cars. Sell your used vehicle in 3 weeks and earn 30% over dealer value.',
  },
  {
    title: 'Groundfloor',
    role: 'Co-founder',
    url: 'https://groundfloor.us',
    img: 'groundfloor.jpg',
    info: 'The first crowdfunding community for real estate. Back independent builders with secured loans that pay 5-26% annually.',
  },
  {
    title: 'Socialytics',
    role: 'Co-founder',
    url: 'http://socialytics.blakeperdue.com/',
    img: 'socialytics.jpg',
    info: 'Social media analytics for digital marketers. Insights into social media marketing effectiveness. Clients included Intel, Crayola and DirecTV.',
  },
  {
    title: 'Data Validation',
    role: 'Product Designer',
    url: 'https://datavalidation.com',
    img: 'datavalidation.jpg',
    info: 'Avoid the spam box. Clean and maintain your email marketing list to safeguard your email sender reputation.',
  },
  // {
  //   title: 'XXXXXXX',
  //   role: 'XXXXXXX',
  //   url: 'https://XXXXXXX.com',
  //   img: 'XXXXXXX.png',
  //   info: 'XXXXXXX',
  // },
]


export default ProjectsData
